APIs on per URL basis
project-eve/eve pull request #73
Opened 2019-05-08 05:44 UTC by vtapaskar

Signed-off-by: Vijay Tapaskar <vijay@zededa.com>

- Doing APIs on per URL basis
- Starting to cleanup the hierarchy of structures

2019-05-08 06:13 UTC, deitch commented
Is this intended to replace #64?

2019-05-08 06:20 UTC, deitch commented
Also yetus checks are failing.

2019-05-08 06:27 UTC, rvs commented
Hey @deitch -- lets move the discussion back to #64 since this is not standalone and for as long as it is WIP -- lets discuss it there. I'll push @zedvijay changes into #64 so we're all on the same page.

2019-05-08 06:30 UTC, deitch requested changes
The `go_package` part is off. It should reflect not where this is, but rather where consumers will import it. We generate our sdk outputs to `github.com/zededa/eve/sdk/go/<package>`, so it should be there. Other than that, nice step ahead.

2019-05-08 06:30 UTC, deitch commented on api/config/appconfig.proto
> +option go_package  = "github.com/zededa/api/config";
I think this is incorrect. The value of `go_package` is where go consuming packages will find this package. This is correct at `eve/sdk/go/config`, and not `api/config`. So, yes, change it from ending in `/zconfig` to ending in `/config`, but stays under `eve/sdk/go/`

2019-05-08 06:30 UTC, deitch commented on api/config/baseosconfig.proto
> +option go_package  = "github.com/zededa/api/config";
Same as above

2019-05-08 06:30 UTC, deitch commented on api/config/devcommon.proto
> +option go_package  = "github.com/zededa/api/config";
Same as above: `github.com/zededa/eve/sdk/go/config`

2019-05-08 06:30 UTC, deitch commented on api/config/devconfig.proto
> +option go_package  = "github.com/zededa/api/config";
Same as above.

2019-05-08 06:30 UTC, deitch commented on api/config/devmodel.proto
> +option go_package  = "github.com/zededa/api/config";
Same as above: `github.com/zededa/eve/sdk/go/config`

2019-05-08 06:30 UTC, deitch commented on api/config/fw.proto
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
Same as above.

2019-05-08 06:30 UTC, deitch commented on api/config/mesh.proto
> +option go_package  = "github.com/zededa/api/config";
Same as above.

2019-05-08 06:30 UTC, deitch commented on api/config/netcmn.proto
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
Same as above.

2019-05-08 06:30 UTC, deitch commented on api/config/netconfig.proto
> +option go_package = "github.com/zededa/api/config";
Same as above.

2019-05-08 06:30 UTC, deitch commented on api/config/netinst.proto
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
Same as above: `github.com/zededa/eve/sdk/go/config`

2019-05-08 06:30 UTC, deitch commented on api/config/storage.proto
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
Same as above.

2019-05-08 06:30 UTC, deitch commented on api/config/vm.proto
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
Same as above

2019-05-08 06:30 UTC, deitch commented on api/logs/log.proto
> +option go_package  = "github.com/zededa/api/logs";
This should go to `github.com/zededa/eve/sdk/go/logs`

2019-05-08 06:30 UTC, deitch commented on api/metrics/metrics.proto
> +option go_package  = "github.com/zededa/api/metrics";
Same as above. This should be `github.com/zededa/eve/sdk/go/metrics`

2019-05-08 06:30 UTC, deitch commented on api/register/register.proto
> +option go_package  = "github.com/zededa/api/register";
Same as above. This should be `github.com/zededa/eve/sdk/go/register`

2019-05-08 06:31 UTC, deitch commented
> lets move the discussion back to #64 since this is not standalone and for as long as it is WIP 

OK @rvs , although only saw this after doing a full review. Overall, it looks good, but the `go_package` parts are off. So let's not import this directly in there until those are fixed? Avoid double-work?

2019-05-08 06:33 UTC, zedvijay commented
Thanks Avi, will fix those tomorrow am.

> On May 7, 2019, at 11:30 PM, Avi Deitcher <notifications@github.com> wrote:
> 
> @deitch requested changes on this pull request.
> 
> The go_package part is off. It should reflect not where this is, but rather where consumers will import it. We generate our sdk outputs to github.com/zededa/eve/sdk/go/<package>, so it should be there. Other than that, nice step ahead.
> 
> In api/config/appconfig.proto <https://github.com/zededa/eve/pull/73#discussion_r281927339>:
> 
> > @@ -3,15 +3,13 @@
>  
>  syntax = "proto3";
>  
> -option go_package  = "github.com/zededa/eve/sdk/go/zconfig";
> +option go_package  = "github.com/zededa/api/config";
> I think this is incorrect. The value of go_package is where go consuming packages will find this package. This is correct at eve/sdk/go/config, and not api/config. So, yes, change it from ending in /zconfig to ending in /config, but stays under eve/sdk/go/
> 
> In api/config/baseosconfig.proto <https://github.com/zededa/eve/pull/73#discussion_r281927421>:
> 
> > @@ -3,7 +3,7 @@
>  
>  syntax = "proto3";
>  
> -option go_package  = "github.com/zededa/eve/sdk/go/zconfig";
> +option go_package  = "github.com/zededa/api/config";
> Same as above
> 
> In api/config/devcommon.proto <https://github.com/zededa/eve/pull/73#discussion_r281927585>:
> 
> > @@ -0,0 +1,54 @@
> +// Copyright(c) 2017-2018 Zededa, Inc.
> +// All rights reserved.
> +
> +syntax = "proto3";
> +
> +option go_package  = "github.com/zededa/api/config";
> Same as above: github.com/zededa/eve/sdk/go/config
> 
> In api/config/devconfig.proto <https://github.com/zededa/eve/pull/73#discussion_r281927820>:
> 
> > @@ -0,0 +1,53 @@
> +// Copyright(c) 2017-2018 Zededa, Inc.
> +// All rights reserved.
> +
> +syntax = "proto3";
> +
> +option go_package  = "github.com/zededa/api/config";
> Same as above.
> 
> In api/config/devmodel.proto <https://github.com/zededa/eve/pull/73#discussion_r281927896>:
> 
> > @@ -0,0 +1,58 @@
> +// Copyright(c) 2017-2018 Zededa, Inc.
> +// All rights reserved.
> +
> +syntax = "proto3";
> +
> +option go_package  = "github.com/zededa/api/config";
> Same as above: github.com/zededa/eve/sdk/go/config
> 
> In api/config/fw.proto <https://github.com/zededa/eve/pull/73#discussion_r281927933>:
> 
> >  option java_package = "com.zededa.cloud.uservice.proto";
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
> Same as above.
> 
> In api/config/mesh.proto <https://github.com/zededa/eve/pull/73#discussion_r281927954>:
> 
> > @@ -0,0 +1,26 @@
> +// Copyright(c) 2017-2018 Zededa, Inc.
> +// All rights reserved.
> +
> +syntax = "proto3";
> +
> +option go_package  = "github.com/zededa/api/config";
> Same as above.
> 
> In api/config/netcmn.proto <https://github.com/zededa/eve/pull/73#discussion_r281927982>:
> 
> >  option java_package = "com.zededa.cloud.uservice.proto";
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
> Same as above.
> 
> In api/config/netconfig.proto <https://github.com/zededa/eve/pull/73#discussion_r281928012>:
> 
> > @@ -3,8 +3,8 @@
>  
>  syntax = "proto3";
>  
> +option go_package = "github.com/zededa/api/config";
> Same as above.
> 
> In api/config/netinst.proto <https://github.com/zededa/eve/pull/73#discussion_r281928058>:
> 
> >  option java_package = "com.zededa.cloud.uservice.proto";
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
> Same as above: github.com/zededa/eve/sdk/go/config
> 
> In api/config/storage.proto <https://github.com/zededa/eve/pull/73#discussion_r281928398>:
> 
> >  option java_package = "com.zededa.cloud.uservice.proto";
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
> Same as above.
> 
> In api/config/vm.proto <https://github.com/zededa/eve/pull/73#discussion_r281928564>:
> 
> >  option java_package = "com.zededa.cloud.uservice.proto";
> -option go_package = "github.com/zededa/eve/sdk/go/zconfig";
> Same as above
> 
> In api/logs/log.proto <https://github.com/zededa/eve/pull/73#discussion_r281928630>:
> 
> > @@ -4,7 +4,7 @@
>  syntax = "proto3";
>  
>  import "google/protobuf/timestamp.proto";
> -option go_package  = "github.com/zededa/eve/sdk/go/zmet";
> +option go_package  = "github.com/zededa/api/logs";
> This should go to github.com/zededa/eve/sdk/go/logs
> 
> In api/metrics/metrics.proto <https://github.com/zededa/eve/pull/73#discussion_r281929040>:
> 
> > @@ -0,0 +1,296 @@
> +// Copyright(c) 2017-2018 Zededa, Inc.
> +// All rights reserved.
> +
> +syntax = "proto3";
> +
> +import "google/protobuf/timestamp.proto";
> +option go_package  = "github.com/zededa/api/metrics";
> Same as above. This should be github.com/zededa/eve/sdk/go/metrics
> 
> In api/register/register.proto <https://github.com/zededa/eve/pull/73#discussion_r281929136>:
> 
> > @@ -3,7 +3,7 @@
>  
>  syntax = "proto3";
>  
> -option go_package  = "github.com/zededa/eve/sdk/go/zmet";
> +option go_package  = "github.com/zededa/api/register";
> Same as above. This should be github.com/zededa/eve/sdk/go/register
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/zededa/eve/pull/73#pullrequestreview-234882262>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AG4ZUXFXGFH6XO4U7UEALJDPUJXRPANCNFSM4HLOSBFQ>.
>

2019-05-08 06:33 UTC, deitch commented
Cool @zedvijay !

2019-05-08 06:34 UTC, rvs commented
Hey @zedvijay its not just what @deitch mentioned but also the questions that he asked on #64 

Since you guys didn't wait for me to update that - and we now have the split reviews between the two -- @deitch can you copy your questions into this thread? Some of them are important to be answered.

I'm closing #64 now

2019-05-08 06:36 UTC, rvs commented
And one last thing @deitch any chance you can help update the docs for it (based on the answers to your questions + what's in the PR)?

2019-05-08 06:39 UTC, deitch commented
From the other issue (edited), some questions:

1. Have we updated the consuming code in `pkg/pillar/` (and anywhere else in zedcloud)? It isn't strictly necessary if we versionize it properly, but we haven't done that yet, so we should update them in sync.
2. If we are removing the z prefix to the package, should we not also remove it from the messages? 
E.g.

```
  ZmNop = 0;
  ZmDevice = 1;
  ZmApp = 3;
}
```

should just be

```
  MNop = 0;
  MDevice = 1;
  MApp = 3;
}
```

My understanding is that there might be an issue with internal messages inside either zedcloud or `pkg/pillar/`, so I am not assuming this to be good.
To be clear, it also is OK to merge this with the `Z` in place, and then remove those (if we can) as a separate PR.

3. Once confirmed, immediately after merging in or as part of this PR, we should update the API document.

2019-05-08 06:39 UTC, deitch commented
> And one last thing @deitch any chance you can help update the docs for it 

Definitely. Let's get this ready to run first.

2019-05-08 06:42 UTC, zedvijay commented
Avi,

Please inline.

Vijay

> On May 7, 2019, at 11:39 PM, Avi Deitcher <notifications@github.com> wrote:
> 
> From the other issue (edited), some questions:
> 
> Have we updated the consuming code in pkg/pillar/ (and anywhere else in zedcloud)? It isn't strictly necessary if we versionize it properly, but we haven't done that yet, so we should update them in sync.
This is not done yet. It will be follow up commit. Controller side of changes are already done, we should start changing the pillar code.

> If we are removing the z prefix to the package, should we not also remove it from the messages?
> E.g.
>   ZmNop = 0;
>   ZmDevice = 1;
>   ZmApp = 3;
> }
> should just be
> 
>   MNop = 0;
>   MDevice = 1;
>   MApp = 3;
> }
> My understanding is that there might be an issue with internal messages inside either zedcloud or pkg/pillar/, so I am not assuming this to be good.
> To be clear, it also is OK to merge this with the Z in place, and then remove those (if we can) as a separate PR.
> 
> 

100% agree. Also I would like to add documentation around what each of these things means inline. Thats next thing on my plate.

> Once confirmed, immediately after merging in or as part of this PR, we should update the API document.
Either way is fine by me.


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/zededa/eve/pull/73#issuecomment-490367272>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AG4ZUXCH642XJON7ACFPI6LPUJYQZANCNFSM4HLOSBFQ>.
>

2019-05-08 06:42 UTC, rvs commented
I'll need @zedvijay to provide answers to some of these, but here's my take:
   * we haven't updated what's vendored in pillar yet -- that'll be a separate follow up PR (based on the vendoring mechanics I describe in the next bullet item)
   * we're no longer vendoring api explicitly because it is done at the pillar level (based on the go.mod)
   * yes it would be nice to get rid of z-prefix, but I'll leave it up to @zedvijay to decide if it is too much of a brain surgery at this point

Makes sense?

2019-05-08 06:47 UTC, deitch commented
> This is not done yet. It will be follow up commit. Controller side of changes are already done, we should start changing the pillar code.

Sounds good. According to what Roman said above, we are versioning it in with go modules. As long as we are tying it to specific commit, we are good. These changes affect other commits when run to `sdk/go/`, so we have the flexibility to do it in sequential commits. Nice.

> If we are removing the z prefix to the package, should we not also remove it from the messages? E.g. ZmNop = 0; ZmDevice = 1; ZmApp = 3; } should just be MNop = 0; MDevice = 1; MApp = 3; } My understanding is that there might be an issue with internal messages inside either zedcloud or pkg/pillar/, so I am not assuming this to be good. To be clear, it also is OK to merge this with the Z in place, and then remove those (if we can) as a separate PR.
> 100% agree. Also I would like to add documentation around what each of these things means inline. Thats next thing on my plate.

That would be appreciated. Even as I wrote the API doc/spec with everyone's help, some of the specific messages were a little opaque to me.

Also @rvs wrote:

> Makes sense?

Yes, indeed. All on the same page. Sounds like we should:

1. Fix the `go_package` issue
2. Fix whatever is causing `yetus` to fail tests
3. Merge this one in
4. Update the docs as a separate PR
5. Update pillar as a separate PR

2019-05-08 15:56 UTC, deitch approved these changes

2019-05-08 17:38 UTC, rvs commented
This is back to you @zedvijay it seems ;-)

2019-05-08 17:46 UTC, merged

2019-05-09 09:20 UTC, deitch commented
It would have been better not to have merged this in when CI was failing. Granted, it was just yetus, but we need to be consistent about it going forward.