- Initial commit for TPM functionality
project-eve/eve pull request #74
Opened 2019-05-08 05:52 UTC by cshari-zededa

- Vendored go-tpm package, along with a placeholder cmd, owntpm
- Currently owntpm.go is pretty much empty in terms of tpm functionality
- Will follow up with further commits to populate owntpm.go

Signed-off-by: Hariharasubramanian C S <cshari@zededa.com>

2019-05-08 06:23 UTC, rvs commented
Hey @cshari-zededa seems like the build broke with go fmt complaining about ./cmd/owntpm/owntpm.go you need to fix this.

Also, I'd like to get @deitch feedback on the TPM side of things

Finally, I'm not sure I understand the reason of naming the package owntpm

2019-05-08 07:09 UTC, cshari-zededa commented
Hi @rvs, I have addressed gofmt errors, build is successful now.
owntpm is to take ownership of TPM on first-use or during USB install.  This will clear existing keys and create a new primary key for generating device certificate.  Only a boilerplate code has been committed in owntpm right now. I will follow up with further commits.

2019-05-08 13:58 UTC, eriknordmark commented on pkg/pillar/cmd/owntpm/owntpm.go
> +var (
This looks like a const

2019-05-08 14:00 UTC, eriknordmark commented on pkg/pillar/cmd/owntpm/owntpm.go
> +		fmt.Println(err)
I think it would be useful to import agentlog.Init and logrus like other applications so that we can get the error (and success) logged.

2019-05-08 15:15 UTC, cshari-zededa commented on pkg/pillar/cmd/owntpm/owntpm.go
> +var (
Addressed in the latest commit

2019-05-08 15:15 UTC, cshari-zededa commented on pkg/pillar/cmd/owntpm/owntpm.go
> +		fmt.Println(err)
Addressed in the latest commit.

2019-05-08 16:30 UTC, rvs commented
Hey @cshari-zededa I still think owntpm is not an ideal name. We're build on the idea of microservices in pillar. If you're introducing a microservice please call it for the thing that it manages. IOW, if this module is expected to manage tpm end-to-end we should call it tpmmgr (or perhaps spell it as tpm-mgr) That way we're marking an intent of every microservice clearly.

2019-05-08 16:32 UTC, cshari-zededa commented
> Hey @cshari-zededa I still think owntpm is not an ideal name. We're build on the idea of microservices in pillar. If you're introducing a microservice please call it for the thing that it manages. IOW, if this module is expected to manage tpm end-to-end we should call it tpmmgr (or perhaps spell it as tpm-mgr) That way we're marking an intent of every microservice clearly.

@rvs, I have already changed the name to tpmmgr in the latest commit.

2019-05-08 17:37 UTC, rvs requested changes

2019-05-08 17:37 UTC, rvs commented on pkg/pillar/cmd/tpmmgr/tpmmgr.go
> +package owntpm
This still says owntpm @cshari-zededa

2019-05-09 03:09 UTC, cshari-zededa commented on pkg/pillar/cmd/tpmmgr/tpmmgr.go
> +package owntpm
@rvs Updated it now. Please have a look at the latest.

2019-05-09 09:32 UTC, deitch approved these changes
Finally had a few minutes to take a look. This is fine. 

When you first start using a tpm, you do need to take ownership of it, so owntpm would make sense for a one-time cmd file. Overall, this is a very good starting point, though. Just needs to be rebased on latest master and good to go.

2019-05-09 09:33 UTC, deitch commented
Oh, yes, and needs @rvs to approve this his changes were accepted.

2019-05-09 15:42 UTC, eriknordmark commented on pkg/pillar/cmd/tpmmgr/tpmmgr.go
> +	curpart := *curpartPtr
There is a flag.Parse call missing,

2019-05-09 15:43 UTC, eriknordmark reviewed
I don't see tpmmgr/owntpm being included in zedbox. How do you build and run it?

2019-05-09 16:22 UTC, cshari-zededa commented on pkg/pillar/cmd/tpmmgr/tpmmgr.go
> +	curpart := *curpartPtr
@nordmark 
Addressed your comment in the latest commit.
Currently not including this in zedbox(verifying compilation through direct go build). This is just initial commit to get the go-tpm library in. I am planning to include it in subsequent commits.

2019-05-09 16:32 UTC, rvs approved these changes

2019-05-09 21:34 UTC, rvs commented
Hey @cshari-zededa -- seems like zedbox comment from @nordmark is the only one left to fix before we can merge this. Btw, speaking of zedbox -- don't forget to update the Makefile so that there's a tpmmgr link provided in bin: https://github.com/zededa/eve/blob/master/pkg/pillar/Makefile#L17

2019-05-10 15:05 UTC, merged