pillar migration to the new API layout
project-eve/eve pull request #79
Opened 2019-05-09 01:03 UTC by rvs

This PR has a few commits that should be reviewed separately. First of all, it updates the pillar Go code to use the new API layout. This is mostly non-controversial rename, aside from one place handlemetrics.go where I had to comment out the following code in order to make this compile 
`// setDeprecatedMetricAnyValue(item, i.Value)`

This needs to be looked at by @zedvijay so we can either reshuffle the API a bit more or simply kill the LTE metrics generation (since it isn't really used at all at this point). The root cause of a problem is the new message deprecatedMetricItem  in `api/info/info.proto`

Other than that -- everything is pretty ready to be reviewed

2019-05-09 01:40 UTC, zedvijay commented
@rvs, couple of things. These are only API there is no code operating on it. As controllers vendor these definitions, they would be packaging these in restful API bodies. I strongly feel these should be called APIs in import path rather than SDK.

Second, we need to allow controllers to add decorations if they desire so. This means that we should include original .proto files as well for govendoring support.

2019-05-09 01:41 UTC, zedvijay commented
@rvs, the code changes in itself is ok, other than 2 comments I mentioned above.

2019-05-09 04:44 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/handlemetrics.go
> +		// setDeprecatedMetricAnyValue(item, i.Value)
Please add at least an XXX, and even better, a reference to the info vs metrics use of MetricItem.

2019-05-09 04:48 UTC, eriknordmark commented on pkg/pillar/cmd/zedagent/handlemetrics.go
> +	"github.com/zededa/eve/sdk/go/info"
Why not do 
zinfo 	"github.com/zededa/eve/sdk/go/info"
zmet	"github.com/zededa/eve/sdk/go/metrics"

like you did in handlenetworkinstance in the same directory?
Such consistency would make it easier for the reader.

2019-05-09 04:49 UTC, eriknordmark reviewed
Two nits

2019-05-09 09:25 UTC, deitch requested changes
Overall, looks good. I like the package aliasing to make the transition easier.

Just a request for an addition on the `Makefile`, so that vendoring in can be a one-short `make vendor-pillar` or something similar.

2019-05-09 09:25 UTC, deitch commented on Makefile
> +	@echo Done building sdk, you may want to vendor it into pillar by running \'go mod vendor\' in pkg/pillar
Can we add a `Makefile` target here, so it can be just: `make vendor-pillar` or something similar? Even if we don't make it a dependency (which we eventually might), let's at least make this easier to do.

2019-05-09 16:34 UTC, rvs commented on pkg/pillar/cmd/zedagent/handlemetrics.go
> +		// setDeprecatedMetricAnyValue(item, i.Value)
Actually @nordmark I was hoping you can help restructure the code in time so we can fix it for real ;-) Any chance of that?

2019-05-09 16:36 UTC, rvs commented on pkg/pillar/cmd/zedagent/handlemetrics.go
> +	"github.com/zededa/eve/sdk/go/info"
We can do that, sure. Its just that in files where I didn't find any conflicts with info as an identifier  I think it makes it much cleaner to actually transition to info as a name (with us getting rid of z-names for EVE and all).

I can add // XXX transition to the files where it is still zmet so we can fix it eventually, but I think it needs to be fixed.

2019-05-09 23:38 UTC, rvs commented
Hey @deitch I updated the Makefile logic as per your comments and I also regularized imports as @nordmark requested.

Now one final question I'd like to resolve is the one brought up by @zedvijay 

Personally, I'm on the fence as to whether to keep generated go and python files in a different folder (sdk) or to have them right next to proto files in (api). This, of course, doesn't change anything in the implementation -- it is just naming, but I think to @zedvijay point it is important for us to get this right out of the gate.

I've done a bit of sleuthing and it seems that Kubernetes, Cloud Foundry and Docker are actually mixing proto files and go files in the same folder. I'm not sure whether it was because of some toolchain limitations or something like that, but the result is that the import paths on the go side look uniform between where proto files are and where sdk is.

I'm actually starting to agree with @zedvijay that perhaps it is a better option for us as well.

2019-05-10 11:00 UTC, deitch approved these changes

2019-05-10 11:09 UTC, deitch commented
@zedvijay wrote (and @rvs commented):

> These are only API there is no code operating on it. As controllers vendor these definitions, they would be packaging these in restful API bodies. I strongly feel these should be called APIs in import path rather than SDK.
> 
> Second, we need to allow controllers to add decorations if they desire so. This means that we should include original .proto files as well for govendoring support.

I am not at all attached to calling it `sdk`. The real goal with that earlier PR was to get all 3+ parts - the messages definitions in protobuf files; the go generated code; the python generated code; maybe more langs going forward - in sane manageable places. As I recall, our original attempt had the python files polluting the root directory, the go files interleaved with the protobufs, etc. We just needed to add _some_ clear structure, but it didn't at all have to be final.

With respect to "sdk"... I don't care much. We can call it api too.

The primary goal there remains: keep things clean. Importing a directory in any language should give me clean files for that language: node should give me `.js` files (if we ever decide to do that); go should give me `.go` files; python should give me `.py` files; etc. and never the twain shall meet.

So if we want to switch from:

```
   |
   |- sdk/
   |    |- go/ (go files here)
   |    |- python/ (py files here)
   |
   |- api/ (protobufs here)
```

to something more like

```
   |- api/
        |- src/ (protobufs here)
        |- go/ (go files here)
        |- python/ (py files here)
```

or similar, i.e. all under an `api/` dir, that is fine too. 

The one thing I think we should not have is something that looks like

```
   |- api/
        |- foo.proto  file
        |- foo.pb.go  file
        |- foo.pb.py  file
        |- foo.pb.js  file
        |- bar.proto  file
        |- bar.pb.go  file
        |- bar.pb.py  file
        |- bar.pb.js  file
```

I can see imports in one language trying to parse others, and heaven help us as we have all of these dependencies. Call it safe imports.

2019-05-10 11:10 UTC, deitch commented
Also needs rebase.

2019-05-10 13:48 UTC, justincormack commented
Most of the Docker/containerd ones only produce Go, and Go is fine ignoring files it doesn't know about in imports. But once you have more than once language I would split the protos into their own directory.

2019-05-10 15:23 UTC, rvs commented
I like the above suggestion by @deitch 

How about we settle on something like: 
```
|- api/
        |- proto/ (protobufs here)
        |- go/ (go files here)
        |- python/ (py files here)
```
@zedvijay & @nordmark  what do you think?

2019-05-10 18:37 UTC, zedvijay commented
Sounds good to me

> On May 10, 2019, at 8:23 AM, Roman V Shaposhnik <notifications@github.com> wrote:
> 
> I like the above suggestion by @deitch <https://github.com/deitch>
> How about we settle on something like:
> 
> |- api/
>         |- proto/ (protobufs here)
>         |- go/ (go files here)
>         |- python/ (py files here)
> @zedvijay <https://github.com/zedvijay> & @nordmark <https://github.com/nordmark> what do you think?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/zededa/eve/pull/79#issuecomment-491328163>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AG4ZUXCYLQXMUOVHHIWFCQDPUWHPVANCNFSM4HLWJZRA>.
>

2019-05-10 23:42 UTC, rvs commented
Hey @nordmark @deitch @zedvijay I've moved this to lf-edge/eve -- the change is already there so please go and check out if it looks acceptable to you.

I also asked folks on the cloud side to start importing from lf-edge/eve/api and see if their builds still work.

2019-05-10 23:42 UTC, closed without merging